// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace_types.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "trace_types.pb.h"

#include <utility>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* TraceInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TraceInfo_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TraceInfo_Sampling_descriptor_ = NULL;

}  // namespace

void protobuf_AssignDesc_trace_5ftypes_2eproto() {
  protobuf_AddDesc_trace_5ftypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "trace_types.proto");
  GOOGLE_CHECK(file != NULL);
  TraceInfo_descriptor_ = file->message_type(0);
  static const int TraceInfo_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, session_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, trace_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, span_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, parent_span_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, sampling_),
  };
  TraceInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TraceInfo_descriptor_,
      TraceInfo::default_instance_,
      TraceInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TraceInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TraceInfo));
  TraceInfo_Sampling_descriptor_ = TraceInfo_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_trace_5ftypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TraceInfo_descriptor_, &TraceInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_trace_5ftypes_2eproto() {
  delete TraceInfo::default_instance_;
  delete TraceInfo_reflection_;
}

void protobuf_AddDesc_trace_5ftypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021trace_types.proto\022\014bgs.protocol\"\275\001\n\tTr"
    "aceInfo\022\022\n\nsession_id\030\001 \001(\t\022\020\n\010trace_id\030"
    "\002 \001(\t\022\017\n\007span_id\030\003 \001(\t\022\026\n\016parent_span_id"
    "\030\004 \001(\t\0229\n\010sampling\030\005 \001(\0162 .bgs.protocol."
    "TraceInfo.Sampling:\005DEFER\"&\n\010Sampling\022\007\n"
    "\003YES\020\000\022\006\n\002NO\020\001\022\t\n\005DEFER\020\002B\"\n\rbnet.protoc"
    "olB\017TraceTypesProtoH\001", 261);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "trace_types.proto", &protobuf_RegisterTypes);
  TraceInfo::default_instance_ = new TraceInfo();
  TraceInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_trace_5ftypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_trace_5ftypes_2eproto {
  StaticDescriptorInitializer_trace_5ftypes_2eproto() {
    protobuf_AddDesc_trace_5ftypes_2eproto();
  }
} static_descriptor_initializer_trace_5ftypes_2eproto_;
// ===================================================================

const ::google::protobuf::EnumDescriptor* TraceInfo_Sampling_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TraceInfo_Sampling_descriptor_;
}
bool TraceInfo_Sampling_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TraceInfo_Sampling TraceInfo::YES;
const TraceInfo_Sampling TraceInfo::NO;
const TraceInfo_Sampling TraceInfo::DEFER;
const TraceInfo_Sampling TraceInfo::Sampling_MIN;
const TraceInfo_Sampling TraceInfo::Sampling_MAX;
const int TraceInfo::Sampling_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int TraceInfo::kSessionIdFieldNumber;
const int TraceInfo::kTraceIdFieldNumber;
const int TraceInfo::kSpanIdFieldNumber;
const int TraceInfo::kParentSpanIdFieldNumber;
const int TraceInfo::kSamplingFieldNumber;
#endif  // !_MSC_VER

TraceInfo::TraceInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.TraceInfo)
}

void TraceInfo::InitAsDefaultInstance() {
}

TraceInfo::TraceInfo(const TraceInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.TraceInfo)
}

void TraceInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  session_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  trace_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  span_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parent_span_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sampling_ = 2;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TraceInfo::~TraceInfo() {
  // @@protoc_insertion_point(destructor:bgs.protocol.TraceInfo)
  SharedDtor();
}

void TraceInfo::SharedDtor() {
  if (session_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete session_id_;
  }
  if (trace_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete trace_id_;
  }
  if (span_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete span_id_;
  }
  if (parent_span_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete parent_span_id_;
  }
  if (this != default_instance_) {
  }
}

void TraceInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TraceInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TraceInfo_descriptor_;
}

const TraceInfo& TraceInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_trace_5ftypes_2eproto();
  return *default_instance_;
}

TraceInfo* TraceInfo::default_instance_ = NULL;

TraceInfo* TraceInfo::New() const {
  return new TraceInfo;
}

void TraceInfo::Clear() {
  if (_has_bits_[0 / 32] & 31) {
    if (has_session_id()) {
      if (session_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        session_id_->clear();
      }
    }
    if (has_trace_id()) {
      if (trace_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        trace_id_->clear();
      }
    }
    if (has_span_id()) {
      if (span_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        span_id_->clear();
      }
    }
    if (has_parent_span_id()) {
      if (parent_span_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        parent_span_id_->clear();
      }
    }
    sampling_ = 2;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TraceInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bgs.protocol.TraceInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string session_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->session_id().data(), this->session_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "session_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_trace_id;
        break;
      }

      // optional string trace_id = 2;
      case 2: {
        if (tag == 18) {
         parse_trace_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trace_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->trace_id().data(), this->trace_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "trace_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_span_id;
        break;
      }

      // optional string span_id = 3;
      case 3: {
        if (tag == 26) {
         parse_span_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_span_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->span_id().data(), this->span_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "span_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_parent_span_id;
        break;
      }

      // optional string parent_span_id = 4;
      case 4: {
        if (tag == 34) {
         parse_parent_span_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parent_span_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parent_span_id().data(), this->parent_span_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "parent_span_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_sampling;
        break;
      }

      // optional .bgs.protocol.TraceInfo.Sampling sampling = 5 [default = DEFER];
      case 5: {
        if (tag == 40) {
         parse_sampling:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::bgs::protocol::TraceInfo_Sampling_IsValid(value)) {
            set_sampling(static_cast< ::bgs::protocol::TraceInfo_Sampling >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bgs.protocol.TraceInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bgs.protocol.TraceInfo)
  return false;
#undef DO_
}

void TraceInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bgs.protocol.TraceInfo)
  // optional string session_id = 1;
  if (has_session_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_id().data(), this->session_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->session_id(), output);
  }

  // optional string trace_id = 2;
  if (has_trace_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->trace_id().data(), this->trace_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "trace_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->trace_id(), output);
  }

  // optional string span_id = 3;
  if (has_span_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->span_id().data(), this->span_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "span_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->span_id(), output);
  }

  // optional string parent_span_id = 4;
  if (has_parent_span_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_span_id().data(), this->parent_span_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "parent_span_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->parent_span_id(), output);
  }

  // optional .bgs.protocol.TraceInfo.Sampling sampling = 5 [default = DEFER];
  if (has_sampling()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->sampling(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bgs.protocol.TraceInfo)
}

::google::protobuf::uint8* TraceInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bgs.protocol.TraceInfo)
  // optional string session_id = 1;
  if (has_session_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_id().data(), this->session_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->session_id(), target);
  }

  // optional string trace_id = 2;
  if (has_trace_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->trace_id().data(), this->trace_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "trace_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->trace_id(), target);
  }

  // optional string span_id = 3;
  if (has_span_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->span_id().data(), this->span_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "span_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->span_id(), target);
  }

  // optional string parent_span_id = 4;
  if (has_parent_span_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parent_span_id().data(), this->parent_span_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "parent_span_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->parent_span_id(), target);
  }

  // optional .bgs.protocol.TraceInfo.Sampling sampling = 5 [default = DEFER];
  if (has_sampling()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->sampling(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bgs.protocol.TraceInfo)
  return target;
}

int TraceInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string session_id = 1;
    if (has_session_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->session_id());
    }

    // optional string trace_id = 2;
    if (has_trace_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->trace_id());
    }

    // optional string span_id = 3;
    if (has_span_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->span_id());
    }

    // optional string parent_span_id = 4;
    if (has_parent_span_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->parent_span_id());
    }

    // optional .bgs.protocol.TraceInfo.Sampling sampling = 5 [default = DEFER];
    if (has_sampling()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->sampling());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TraceInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TraceInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TraceInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TraceInfo::MergeFrom(const TraceInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_id()) {
      set_session_id(from.session_id());
    }
    if (from.has_trace_id()) {
      set_trace_id(from.trace_id());
    }
    if (from.has_span_id()) {
      set_span_id(from.span_id());
    }
    if (from.has_parent_span_id()) {
      set_parent_span_id(from.parent_span_id());
    }
    if (from.has_sampling()) {
      set_sampling(from.sampling());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TraceInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TraceInfo::CopyFrom(const TraceInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TraceInfo::IsInitialized() const {
  return true;
}

void TraceInfo::Swap(TraceInfo* other) {
  if (other != this) {
    std::swap(session_id_, other->session_id_);
    std::swap(trace_id_, other->trace_id_);
    std::swap(span_id_, other->span_id_);
    std::swap(parent_span_id_, other->parent_span_id_);
    std::swap(sampling_, other->sampling_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TraceInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TraceInfo_descriptor_;
  metadata.reflection = TraceInfo_reflection_;
  return metadata;
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)
