CREATE USER IF NOT EXISTS 'arguscore'@'%' IDENTIFIED BY 'arguscore' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;

GRANT USAGE ON * . * TO 'arguscore'@'%';

CREATE DATABASE IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `characters` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `auth` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `hotfixes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON `world` . * TO 'arguscore'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `characters` . * TO 'arguscore'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `auth` . * TO 'arguscore'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `hotfixes` . * TO 'arguscore'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;