// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_extensions/field_options.proto

#ifndef PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED
#define PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/descriptor.pb.h"
#include "Define.h" // for TC_PROTO_API
// @@protoc_insertion_point(includes)

namespace bgs {
namespace protocol {

// Internal implementation detail -- do not call these.
void TC_PROTO_API protobuf_AddDesc_global_5fextensions_2ffield_5foptions_2eproto();
void protobuf_AssignDesc_global_5fextensions_2ffield_5foptions_2eproto();
void protobuf_ShutdownFile_global_5fextensions_2ffield_5foptions_2eproto();

class BGSFieldOptions;

enum LogOption {
  HIDDEN = 1,
  HEX = 2
};
TC_PROTO_API bool LogOption_IsValid(int value);
const LogOption LogOption_MIN = HIDDEN;
const LogOption LogOption_MAX = HEX;
const int LogOption_ARRAYSIZE = LogOption_MAX + 1;

TC_PROTO_API const ::google::protobuf::EnumDescriptor* LogOption_descriptor();
inline const ::std::string& LogOption_Name(LogOption value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogOption_descriptor(), value);
}
inline bool LogOption_Parse(
    const ::std::string& name, LogOption* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogOption>(
    LogOption_descriptor(), name, value);
}
// ===================================================================

class TC_PROTO_API BGSFieldOptions : public ::google::protobuf::Message {
 public:
  BGSFieldOptions();
  virtual ~BGSFieldOptions();

  BGSFieldOptions(const BGSFieldOptions& from);

  inline BGSFieldOptions& operator=(const BGSFieldOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BGSFieldOptions& default_instance();

  void Swap(BGSFieldOptions* other);

  // implements Message ----------------------------------------------

  BGSFieldOptions* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BGSFieldOptions& from);
  void MergeFrom(const BGSFieldOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .bgs.protocol.LogOption log = 1;
  inline bool has_log() const;
  inline void clear_log();
  static const int kLogFieldNumber = 1;
  inline ::bgs::protocol::LogOption log() const;
  inline void set_log(::bgs::protocol::LogOption value);

  // optional bool shard_key = 2;
  inline bool has_shard_key() const;
  inline void clear_shard_key();
  static const int kShardKeyFieldNumber = 2;
  inline bool shard_key() const;
  inline void set_shard_key(bool value);

  // @@protoc_insertion_point(class_scope:bgs.protocol.BGSFieldOptions)
 private:
  inline void set_has_log();
  inline void clear_has_log();
  inline void set_has_shard_key();
  inline void clear_has_shard_key();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int log_;
  bool shard_key_;
  friend void TC_PROTO_API protobuf_AddDesc_global_5fextensions_2ffield_5foptions_2eproto();
  friend void protobuf_AssignDesc_global_5fextensions_2ffield_5foptions_2eproto();
  friend void protobuf_ShutdownFile_global_5fextensions_2ffield_5foptions_2eproto();

  void InitAsDefaultInstance();
  static BGSFieldOptions* default_instance_;
};
// ===================================================================

// ===================================================================

static const int kFieldOptionsFieldNumber = 90000;
TC_PROTO_API extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::BGSFieldOptions >, 11, false >
  field_options;

// ===================================================================

// BGSFieldOptions

// optional .bgs.protocol.LogOption log = 1;
inline bool BGSFieldOptions::has_log() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BGSFieldOptions::set_has_log() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BGSFieldOptions::clear_has_log() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BGSFieldOptions::clear_log() {
  log_ = 1;
  clear_has_log();
}
inline ::bgs::protocol::LogOption BGSFieldOptions::log() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSFieldOptions.log)
  return static_cast< ::bgs::protocol::LogOption >(log_);
}
inline void BGSFieldOptions::set_log(::bgs::protocol::LogOption value) {
  assert(::bgs::protocol::LogOption_IsValid(value));
  set_has_log();
  log_ = value;
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSFieldOptions.log)
}

// optional bool shard_key = 2;
inline bool BGSFieldOptions::has_shard_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BGSFieldOptions::set_has_shard_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BGSFieldOptions::clear_has_shard_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BGSFieldOptions::clear_shard_key() {
  shard_key_ = false;
  clear_has_shard_key();
}
inline bool BGSFieldOptions::shard_key() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSFieldOptions.shard_key)
  return shard_key_;
}
inline void BGSFieldOptions::set_shard_key(bool value) {
  set_has_shard_key();
  shard_key_ = value;
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSFieldOptions.shard_key)
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

#ifndef SWIG
namespace google {
namespace protobuf {
template <> struct is_proto_enum< ::bgs::protocol::LogOption> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bgs::protocol::LogOption>() {
  return ::bgs::protocol::LogOption_descriptor();
}
}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_global_5fextensions_2ffield_5foptions_2eproto__INCLUDED
